- hosts: localhost
  connection: local
  become: true
  pre_tasks:
  - include_tasks: tasks/updateALL.yml
  tasks:
#  - include_tasks: tasks/packages.yml
  - include_tasks: tasks/serverConfig.yml

#  handlers:
#  - name: Restart systemd-timedated
#    service:
#      name: systemd-timedated
#      state: restarted
#  tasks:
#  - name: Set timezone
#    shell: timedatectl set-timezone EST
#    notify: Restart systemd-timedated  
