---
- hosts: all
  pre_tasks:
  - include_tasks: tasks/updateALL.yml
  tasks:
  - include_tasks: tasks/packages.yml
  - include_tasks: tasks/serverConfig.yml
#
#- hosts: testing
#  become: true
#  tasks:
 # - include_tasks:  task/NTP_timeConfig.yml