---
- hosts: all
  become: true
  pre_tasks:
  - include_tasks: tasks/updateALL.yml
  tasks:
  - include_tasks: tasks/packages.yml
  - include_tasks: tasks/serverConfig.yml
  - include_tasks: tasks/HAL_keyUpkeep.yml
#
#- hosts: testing
#  become: true
#  tasks:
 # - include_tasks: task/NTP_timeConfig.yml