---
-
  name: Add HAL ssh key
  become: true
  tags: always
  authorized_key:
    user: HAL_ansible
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFPbHqTPxqkKIVO0cYDSM5esooxmfNr6ECa1k5YxGJ4D HAL_ansible FarmNet.Lab Key"
