--- 
-
  name: "Install Debian Packages"
  become: true
  package:
    name:
      - htop
      - ntp
      - tmux
      - lynis
      ### just added make config
      - vim
  when: "ansible_distribution in[\"Ubuntu\", \"Debian\", \"Pop!_OS\"]"