--- 
-
  become: true
  name: "Linux Packages (servers)"
  package: ### change to packages (universal)
    name:
      - htop
      - ntp
      - tmux
      - lynis
      - vim ### just added make config
 # when: "ansible_distribution in[\"Ubuntu\", \"Debian\", \"Pop!_OS\"]"