--- 
-
  name: "Install Debian Packages"
  package:
    name:
      - htop
      - ntp
      - tmux
      - lynis
      - vim ### just added make config
  when: "ansible_distribution in[\"Ubuntu\", \"Debian\", \"Pop!_OS\"]"