---
  - name: serverConfig Files
    become: true
    copy:
      src: files/dotConfig/htoprc
      dest: .config/htop/htoprc
      force: yes
    copy:
      src: files/dotConfig/vimrc
      dest: .vimrc
    copy:
      src: files/dotConfig/tmux.conf
      dest: .tmux.conf
    copy:
      src: files/dotConfig/bash_aliases
      dest: .bash_aliases
    when: "ansible_distribution in[\"Ubuntu\", \"Debian\", \"Pop!_OS\"]"
