---
-
  name: copy dotConfigfiles
  copy: 
    dest: /home/colin/.config/htop/htoprc
    src: files/dotConfig/htoprc
    owner: colin
    group: colin
  name: "file 'htoprc'"
- 
  copy: 
    dest: /home/colin/.vimrc
    src: files/dotConfig/vimrc
    owner: colin
    group: colin
  name: "file '.vimrc'"
-
  copy:
    dest: /home/colin/.tmux.conf
    src: files/dotConfig/tmux.conf
    owner: colin
    group: colin
  name: "file '.tmux.conf'"
-
  copy:
    dest: /home/colin/.bash_aliases
    src: files/dotConfig/bash_aliases
    owner: colin
    group: colin
  name: "file '.bash_aliases'"

#    when: "ansible_distribution in[\"Ubuntu\", \"Debian\", \"Pop!_OS\"]"


### - Notes - ###

### rename this file something about dot config or dot files

### find a more flexible way to point then at colin home folder