--- 
- 
  become: true
  dnf: 
    update_cache: true
    update_only: true
  name: "update (CentOS)"
  tags: always
  when: "ansible_distribution == \"CentOS\""
- 
  apt: 
    update_cache: true
    upgrade: dist
  become: true
  name: "update (Debian based systems)"
  tags: always
  when: "ansible_distribution in[\"Ubuntu\", \"Debian\", \"Pop!_OS\"]"
- 
#  become: false
#  community.general.homebrew: 
#    update_homebrew: true
#    upgrade_all: true
#  name: "update (MacOSX)"
#  tags: always
#  when: "ansible_distribution == \"MacOSX\""
